### ISSUE TITLE
スケジュール登録フォームの作成

### ISSUE THREAD

**Issue by ryo789** [ryo789/schedule-app#5]
【仕様】
スケジュール登録フォーム(schedules/new)にて、作成する予定の下記データがschedules#createに送られるようにする。
・start_time/end_time
・title/content

・user_id
→schedule_idと共にparticipatesテーブルに登録

※画面イメージは下記参照
https://cacoo.com/diagrams/PCCfbPAygr0K4zT4

【不明点】
■参加ユーザのparticipatesテーブルへの登録について、
・DBに登録されているユーザを一覧表示し、その横のチェックボックスにチェックが付いたユーザのuser_id or インスタンスをControllerへ送りたいが、上手く実装できていない。

・それらを受け取れたとして、schedules#createアクションでどのような処理をを書けばparticipatesテーブルへの反映まで完了できるのか、判明していない。

**Comment by sugitk** [comment]
日付指定周りは個別に書いていってもいいのですが、
http://eonasdan.github.io/bootstrap-datetimepicker/
こういうのを使うのはどうでしょうか。

**Comment by ryo789** [comment]
新規スケジュール登録フォームから、
・Schedule
・Participate
の作成をするための実装は（ひとまず）完了しました。

schedules#create部分やフォームのUI等にはまだまだ改善点がありますが、処理自体は動いています。
